version: '3.8'
services:
 # Portainer is a docker management interface
  portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    environment:
      # Set timezone for logs
      - TZ=Europe/Copenhagen
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  # Watchtower is a docker image updater
  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    environment:
      # Set timezone for logs
      - TZ=Europe/Copenhagen
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Pull every night at 4 AM
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data:
    driver: local